zuul:
  prefix: /
  stripPrefix: true
  routes:
    user-service:
      path: /user/**
      service-id: USER-SERVICE
      stripPrefix: false
    profile-service:
      path: /profile/**
      service-id: PROFILE-SERVICE
      stripPrefix: false
  host:
    connect-timeout-millis: 90000
    socket-timeout-millis: 90000

  ribbon:
    eureka:
      eager-load:
        enabled: true

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 60000

#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000