zuul:
  prefix: /
  stripPrefix: true
  routes:
    user-service:
      path: /user/**
      service-id: USER-SERVICE
      stripPrefix: false
    profile-service:
      path: /profile/**
      service-id: PROFILE-SERVICE
      stripPrefix: false

ribbon:
  eureka:
    enabled: true

# Increase the Hystrix timeout to 60s (globally)
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000